//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardProject.Crm.Model
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public enum Account_IndustryCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Деятельность экстерриториальных организаций", 16)]
		Deyatelnost_eksterritorialnyh_organizacij = 71,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Добыча полезных ископаемых", 4)]
		Dobycha_poleznyh_iskopaemyh = 59,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Финансовая деятельность", 0)]
		Finansovaya_deyatelnost = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Гостиницы и рестораны", 8)]
		Gostinicy_i_restorany = 63,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Государственное управление и оборона; обязательное социальное страхование", 11)]
		Gosudarstvennoe_upravlenie_i_oborona__obyazatelnoe_socialnoe_strahovanie = 66,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Образование", 12)]
		Obrazovanie = 67,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Операции с недвижимым  имуществом,  аренда  и  предоставление услуг", 10)]
		Operacii_s_nedvizhimym__imuschestvom__arenda__i__predostavlenie_uslug = 65,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Оптовая и розничная торговля; ремонт автотранспортных средств, мотоциклов, бытовы" +
			"х устройств и предметов личного пользования", 7)]
		Optovaya_i_roznichnaya_torgovlya__remont_avtotransportnyh_sredstv_motociklov_bytovyh_ustrojstv_i_predmetov_lichnogo_polzovaniya = 62,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Предоставление услуг по домашнему хозяйству", 15)]
		Predostavlenie_uslug_po_domashnemu_hozyajstvu = 70,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Прочие общественные, социальные и персональные услуги", 14)]
		Prochie_obschestvennye_socialnye_i_personalnye_uslugi = 69,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Производство", 5)]
		Proizvodstvo = 60,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Производство и распределение электроэнергии, газа и воды", 6)]
		Proizvodstvo_i_raspredelenie_elektroenergii_gaza_i_vody = 61,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Рыболовство", 3)]
		Rybolovstvo = 58,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Сельское хозяйство, охота и лесное хозяйство", 2)]
		Selskoe_hozyajstvo_ohota_i_lesnoe_hozyajstvo = 57,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Строительство", 1)]
		Stroitelstvo = 53,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Транспорт и связь", 9)]
		Transport_i_svyaz = 64,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Здравоохранение и предоставление социальных услуг", 13)]
		Zdravoohranenie_i_predostavlenie_socialnyh_uslug = 68,
	}
}